
name: CI/CD Pipe

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install psutil

    - name: Run unit tests
      run: |
        python -m unittest discover -s testes

    - name: Build Docker image
      run: |
        docker build -t monitor-app .

    - name: Push Docker image to registry
      run: |
        docker tag monitor-app <seu_registro_docker>/monitor-app:latest
        docker push <seu_registro_docker>/monitor-app:latest

    - name: Deploy to Azure
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'monitor-app'
        slot-name: 'production'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: .
